export type TrabajoFotografia = {
  slug: string;
  aliases?: string[];
  titulo: string;
  detalle: string;
  miniatura?: string;
  imagenes?: string[];
};

export const trabajosFotografia: TrabajoFotografia[] = [
  {
    slug: "fotografia-comercial",
    titulo: "Fotografía Comercial",
    detalle:
      "Sesiones para catálogos físicos y digitales con control de iluminación, fondo y estilo visual de marca.",
  },
  {
    slug: "fotografia-paisajista",
    titulo: "Fotografía Paisajista",
    detalle:
      "Captura de paisajes naturales y urbanos con enfoque estético para contenido editorial, turístico y de marca.",
    miniatura: "/portfolio/fotografia/miniaturas/paisajista/Nissan-49.jpg",
    imagenes: [
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-49.jpg",
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-68.jpg",
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-90.jpg",
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-114.jpg",
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-117.jpg",
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-120.jpg",
      "/portfolio/fotografia/miniaturas/paisajista/Nissan-147.jpg",
    ],
  },
  {
    slug: "cobertura-de-eventos",
    titulo: "Cobertura de Eventos",
    detalle:
      "Registro fotográfico de activaciones, lanzamientos y eventos corporativos con entrega optimizada para difusión.",
    miniatura: "/portfolio/fotografia/miniaturas/eventos/54122352262_4fc0960b8d_o.jpg",
    imagenes: [
      "/portfolio/fotografia/miniaturas/eventos/54122352262_4fc0960b8d_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122352357_dbb348ac94_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122353942_3d14d02129_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122354007_1f177066ec_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122408362_4a61625946_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122409902_96e257e401_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122409932_d762dc3610_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54122410037_fcf1b34be0_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123200436_c021754e75_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123202041_22c7e0376a_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123202256_989300cb75_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123256876_d35debe49e_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123257666_c0a7b5bf5a_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123258536_cbe6fb86a6_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123258621_b916e74928_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123258686_a9e91c4a32_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123258741_e651a5f84e_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123474793_e063a84554_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123474898_35040fc0cc_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123530533_39a4e6f2bf_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123530833_26fa651246_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123530878_25d337673d_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123538389_afea6e5be9_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123540109_50f066fb9b_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123540134_3c67f8f5a4_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123596514_0b835ee160_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123656280_0653535f25_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123656290_753a3c73ec_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123712135_642fbb22c6_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123712615_10a885eb90_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/54123712860_f4952cbd68_o.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-56.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-57.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-60.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-62.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-64.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-66.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-67.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-68.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-69.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-71.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-76.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-77.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-79.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-83.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-85.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-93.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-94.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-95.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-97.jpg",
      "/portfolio/fotografia/miniaturas/eventos/Graduacion%20Sam-99.jpg",
    ],
  },
  {
    slug: "retrato-profesional",
    titulo: "Retrato Profesional",
    detalle:
      "Retratos de equipo y fotografía institucional para fortalecer presencia de marca y comunicación empresarial.",
    miniatura: "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-2.jpg",
    imagenes: [
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-2.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-3.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-4.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-5.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-6.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-7.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-8.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Cumplea%C3%B1os%20Anahi-9.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Ba%C3%B1os-28.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Ba%C3%B1os-31.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Ba%C3%B1os-43.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Graduacion%20Sam-158.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Graduacion%20Sam-170.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Graduacion%20Sam-195.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Graduacion%20Sam-230.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Caminata%20Cascada-12.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Parque-6.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Parque-9.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Parque-50.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Qx-3.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Qx-4.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Qx-8.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Qx-9.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Qx-14.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Fotos%20Qx-25.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Imagen%20PNG%202.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Imagen%20PNG%2027.jpg",
      "/portfolio/fotografia/miniaturas/retrato/Imagen%20PNG%2050.jpg",
    ],
  },
  {
    slug: "fotografia-publicitaria",
    aliases: ["fotografia-gastronomica"],
    titulo: "Fotografía Publicitaria",
    detalle:
      "Producción de campañas visuales para marcas y productos, incluyendo líneas gastronómicas con enfoque comercial.",
    miniatura: "/portfolio/fotografia/miniaturas/publicitaria/fotogastronomia1.jpg",
    imagenes: [
      "/portfolio/fotografia/miniaturas/publicitaria/fotogastronomia1.jpg",
      "/portfolio/fotografia/miniaturas/publicitaria/fotogastronomia2.jpg",
      "/portfolio/fotografia/miniaturas/publicitaria/fotogastronomia3.jpg",
      "/portfolio/fotografia/miniaturas/publicitaria/fotogastonomia4.jpg",
    ],
  },
  {
    slug: "contenido-para-redes",
    titulo: "Contenido para Redes",
    detalle:
      "Series fotográficas verticales y cuadradas listas para publicaciones en Instagram, Facebook y anuncios.",
  },
];
